export const MachineDetail = [
  {
    id: 1,
    objectcode: "KOMAT01",
    objectname: "Komatsu Loader 50 Ton",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 2,
    objectcode: "CNCT01",
    objectname: "CNC Cutter 1000W",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 3,
    objectcode: "WELD01",
    objectname: "Welder Robot X200",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 4,
    objectcode: "ASSB01",
    objectname: "Automated Assembler 3000",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 5,
    objectcode: "DRLL01",
    objectname: "High-Speed Drill 1200",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 6,
    objectcode: "PRNT01",
    objectname: "3D Printer Pro 2024",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 7,
    objectcode: "LASR01",
    objectname: "Precision Laser Cutter",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 8,
    objectcode: "LATH01",
    objectname: "High-Precision Lathe",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 9,
    objectcode: "PLAS01",
    objectname: "Plasma Cutter 5000",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 10,
    objectcode: "WELD02",
    objectname: "Fiber Laser Welder X1",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 11,
    objectcode: "LODR02",
    objectname: "Komatsu Loader 100 Ton",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 12,
    objectcode: "CNCT02",
    objectname: "CNC Cutter 1500W",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 13,
    objectcode: "WELD03",
    objectname: "Welder Robot X250",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 14,
    objectcode: "ASSB02",
    objectname: "Automated Assembler 4000",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 15,
    objectcode: "DRLL02",
    objectname: "High-Speed Drill 1500",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 16,
    objectcode: "PRNT02",
    objectname: "3D Printer Elite 2024",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 17,
    objectcode: "LASR02",
    objectname: "Industrial Laser Cutter",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 18,
    objectcode: "LATH02",
    objectname: "Advanced Lathe Machine",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 19,
    objectcode: "PLAS02",
    objectname: "Plasma Cutter 6000",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 20,
    objectcode: "WELD03",
    objectname: "Fiber Laser Welder X2",
    lat: "0",
    long: "0",
    active: "Y",
  },
];
