export const MachineId = [
  {
    id: 1,
    objectid: "LOADER-001",
    objectname: "LOADER MACHINE 001",
    icongroup: "LOADER",
    iconid: "LOADER",
    countryid: "ID",
    stateid: "EJ",
    cityid: "SBY",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 2,
    objectid: "CUTTER-001",
    objectname: "CUTTER MACHINE 001",
    icongroup: "CUTTER",
    iconid: "CUTTER",
    countryid: "ID",
    stateid: "JKT",
    cityid: "JKT",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 3,
    objectid: "WELDER-001",
    objectname: "WELDER MACHINE 001",
    icongroup: "WELDER",
    iconid: "WELDER",
    countryid: "ID",
    stateid: "BT",
    cityid: "BT",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 4,
    objectid: "ASSEMBLER-001",
    objectname: "ASSEMBLER MACHINE 001",
    icongroup: "ASSEMBLER",
    iconid: "ASSEMBLER",
    countryid: "ID",
    stateid: "SM",
    cityid: "SM",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 5,
    objectid: "DRILL-001",
    objectname: "DRILLING MACHINE 001",
    icongroup: "DRILL",
    iconid: "DRILL",
    countryid: "ID",
    stateid: "JY",
    cityid: "JY",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 6,
    objectid: "PRINTER-001",
    objectname: "3D PRINTER MACHINE 001",
    icongroup: "PRINTER",
    iconid: "PRINTER",
    countryid: "ID",
    stateid: "BDG",
    cityid: "BDG",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 7,
    objectid: "LASER-001",
    objectname: "LASER CUTTING MACHINE 001",
    icongroup: "LASER",
    iconid: "LASER",
    countryid: "ID",
    stateid: "MDN",
    cityid: "MDN",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 8,
    objectid: "LATHE-001",
    objectname: "LATHE MACHINE 001",
    icongroup: "LATHE",
    iconid: "LATHE",
    countryid: "ID",
    stateid: "MLG",
    cityid: "MLG",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 9,
    objectid: "PLASMA-001",
    objectname: "PLASMA CUTTING MACHINE 001",
    icongroup: "PLASMA",
    iconid: "PLASMA",
    countryid: "ID",
    stateid: "SBY",
    cityid: "SBY",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 10,
    objectid: "WELDER-002",
    objectname: "FIBER LASER WELDER 001",
    icongroup: "WELDER",
    iconid: "WELDER",
    countryid: "ID",
    stateid: "BGR",
    cityid: "BGR",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 11,
    objectid: "LOADER-002",
    objectname: "LOADER MACHINE 002",
    icongroup: "LOADER",
    iconid: "LOADER",
    countryid: "ID",
    stateid: "JKT",
    cityid: "JKT",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 12,
    objectid: "CUTTER-002",
    objectname: "CUTTER MACHINE 002",
    icongroup: "CUTTER",
    iconid: "CUTTER",
    countryid: "ID",
    stateid: "BDG",
    cityid: "BDG",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 13,
    objectid: "WELDER-003",
    objectname: "WELDER MACHINE 002",
    icongroup: "WELDER",
    iconid: "WELDER",
    countryid: "ID",
    stateid: "SRG",
    cityid: "SRG",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 14,
    objectid: "ASSEMBLER-002",
    objectname: "ASSEMBLER MACHINE 002",
    icongroup: "ASSEMBLER",
    iconid: "ASSEMBLER",
    countryid: "ID",
    stateid: "SBY",
    cityid: "SBY",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 15,
    objectid: "DRILL-002",
    objectname: "DRILLING MACHINE 002",
    icongroup: "DRILL",
    iconid: "DRILL",
    countryid: "ID",
    stateid: "MLG",
    cityid: "MLG",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 16,
    objectid: "PRINTER-002",
    objectname: "3D PRINTER MACHINE 002",
    icongroup: "PRINTER",
    iconid: "PRINTER",
    countryid: "ID",
    stateid: "MDN",
    cityid: "MDN",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 17,
    objectid: "LASER-002",
    objectname: "LASER CUTTING MACHINE 002",
    icongroup: "LASER",
    iconid: "LASER",
    countryid: "ID",
    stateid: "JKT",
    cityid: "JKT",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 18,
    objectid: "LATHE-002",
    objectname: "LATHE MACHINE 002",
    icongroup: "LATHE",
    iconid: "LATHE",
    countryid: "ID",
    stateid: "EJ",
    cityid: "EJ",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 19,
    objectid: "PLASMA-002",
    objectname: "PLASMA CUTTING MACHINE 002",
    icongroup: "PLASMA",
    iconid: "PLASMA",
    countryid: "ID",
    stateid: "JKT",
    cityid: "JKT",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
  {
    id: 20,
    objectid: "WELDER-004",
    objectname: "FIBER LASER WELDER 002",
    icongroup: "WELDER",
    iconid: "WELDER",
    countryid: "ID",
    stateid: "BDG",
    cityid: "BDG",
    regionid: "ID",
    lat: "0",
    long: "0",
    active: "Y",
  },
];
